version: "3.4"
services:
    web: 
        image: nginx:${NGINX_IMAGE_TAG}
        container_name: blog-nginx
        restart: always
        volumes:
            - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
            - ${CERTBOT_CONF_PATH}:/etc/nginx/ssl
            - ${CERTBOT_DATA_PATH}:/var/www/certbot
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"

  certbot:
    image: certbot/certbot:${CERTBOT_IMAGE_TAG}
    container_name: blog-certbot
    command: certonly --noninteractive --expand --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN} -d ${CERTBOT_SUB_DOMAIN}
    volumes:
      - ${CERTBOT_CONF_PATH}:/etc/letsencrypt
      - ${CERTBOT_LOG_PATH}:/var/log/letsencrypt
      - ${CERTBOT_DATA_PATH}:/var/www/certbot
